networks:
  app_network:
    driver: ${DOCKER_NETWORKS_DRIVER}

volumes:
  postgres_data:
    driver: ${DOCKER_VOLUMES_DRIVER}

  redis_data:
    driver: ${DOCKER_VOLUMES_DRIVER}

  
services:
  
  traefik:
    build:
      context: ./.docker/traefik
      dockerfile: Dockerfile
      args:
        - TRAEFIK_VERSION=${SERVICE_TRAEFIK_VERSION}
    restart: unless-stopped
    environment:
      - CF_API_EMAIL=${SERVICE_TRAEFIK_CF_EMAIL}
      - CF_API_KEY=${SERVICE_TRAEFIK_CF_API_KEY}
    command:
      # log/
      - "--log.level=debug"
      # api
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      # providers
      - "--providers.docker.exposedbydefault=false"
      # entrypoints
      - "--entrypoints.web_insecure.address=:80"
      - "--entrypoints.web_secure.address=:443"
      - "--entrypoints.postgres.address=:5432"
      - "--entrypoints.redis.address=:6379"
      # middleware for redirecting traffic to https
      - "--entrypoints.web_insecure.http.redirections.entryPoint.to=web_secure"
      - "--entrypoints.web_insecure.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web_insecure.http.redirections.entryPoint.permanent=true"
      # tls
      - "--entrypoints.web_secure.http.tls.domains[0].main=${APPS_DOMAIN_NAME}"
      - "--entrypoints.web_secure.http.tls.domains[0].sans=*.${APPS_DOMAIN_NAME}"
      - "--certificatesresolvers.lets_encrypt.acme.storage=/acme.json"
      - "--certificatesresolvers.lets_encrypt.acme.dnsChallenge=true"
      - "--certificatesresolvers.lets_encrypt.acme.dnsChallenge.delayBeforeCheck=0"
      - "--certificatesresolvers.lets_encrypt.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.lets_encrypt.acme.email=${SERVICE_TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.lets_encrypt.acme.dnsChallenge.resolvers=${SERVICE_TRAEFIK_CF_DNS}"
      # the following line is the caserver for testing the certificates generating (comment it for prod)
      # - "--certificatesresolvers.lets_encrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # accesslogb
      - "--accesslog.filepath=/data/access.log"
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - ./.docker/traefik/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - development
      - production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web_secure"
      - "traefik.http.routers.traefik.tls.certresolver=lets_encrypt"
      - "traefik.http.routers.traefik.rule=Host(`${APPS_ENVIRONMENT}-traefik.${APPS_DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.api@internal.loadbalancer.server.port=8888"
      - "traefik.http.routers.traefik.middlewares=access-auth"
      - "traefik.http.middlewares.access-auth.basicauth.realm=Login Required"
      - "traefik.http.middlewares.access-auth.basicauth.users=${SERVICE_TRAEFIK_USER_PASSWORD}"      

  postgres:
    restart: unless-stopped
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
      args:
        - POSTGRES_VERSION=${SERVICE_POSTGRES_VERSION}
    environment:
      - POSTGRES_DB=${SERVICE_POSTGRES_DB}
      - POSTGRES_USER=${SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SERVICE_POSTGRES_PASSWORD}
    networks:
      - app_network
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    profiles:
      - development
      - production
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.service=postgres"
      - "traefik.tcp.routers.postgres.entryPoints=postgres"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"

  redis:
    build:
      context: ./.docker/redis
      args:
        - REDIS_VERSION=${SERVICE_REDIS_VERSION}
    command: --requirepass ${SERVICE_REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - redis_data:/data
    profiles:
      - development
      - production
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.redis.service=redis"
      - "traefik.tcp.routers.redis.entryPoints=redis"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"

  php: 
    build:
      context: ./.docker/drupal-php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${SERVICE_PHP_VERSION}
    restart: unless-stopped
    networks:
      - app_network
    profiles:
      - development
      - production
    environment:
      # By default xdebug extension also disabled.
      PHP_EXTENSIONS_DISABLE: xhprof,spx
      PHP_MAIL_MIXED_LF_AND_CRLF: 'On'
      DRUSH_OPTIONS_URI: "http://${APPS_ENVIRONMENT}-admin.${APPS_DOMAIN_NAME}"
    volumes:
      - $APP_BACK_OFFICE_PATH_IN_HOST:/var/www/html:cached

  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=${SERVICE_NGINX_VERSION}
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - app_network
    profiles:
      - development
      - production
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $SERVICE_NGINX_VHOST_PRESET
    volumes:
      - $APP_BACK_OFFICE_PATH_IN_HOST:/var/www/html:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=web_secure"
      - "traefik.http.routers.nginx.tls.certresolver=lets_encrypt"
      - "traefik.http.routers.nginx.rule=Host(`${APPS_ENVIRONMENT}-admin.${APPS_DOMAIN_NAME}`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
